#!/bin/bash

# up to you (me) if you want to run this as a file or copy paste at your leisure

# Shell Script to copy a specific manager files (based on my needs)
# run with alias "newmanager"

# Ask for the administrator password upfront
sudo -v

clear

# Variables
BOWER="bower"
GRUNT="grunt"
COMPASS="compass"
COMPOSER="composer"
NPM="npm"
GEMRAKE="rake"
MAKEFILE="make"

DOWNLOADS="${HOME}/Downloads"
MANAGERS_TARBALL_PATH="https://github.com/vitorbritto/managers/tarball/master"
MANAGERS_DIRECTORY="src"
STYLE="$(tput setaf 37)$(tput bold)[ ? ]$(tput sgr0)"
UTILS_DIRECTORY="${HOME}/.forcefiles/lib/utils"

source ${UTILS_DIRECTORY}

# Let me introduce myself
clear
figlet -f smslant inject manager

# if do not have ./src folder create one
if [[ ! -d ${MANAGERS_DIRECTORY} ]]; then
    e_header "Initializing..."
    mkdir -p ${MANAGERS_DIRECTORY}
fi

# Get the tarball
e_header "Downloading repository..."
curl -fsSLo ${DOWNLOADS}/managers.tar.gz ${MANAGERS_TARBALL_PATH}

# Extract to the boilerplate directory
e_header "Extracting files..."
tar -zxf ${DOWNLOADS}/managers.tar.gz --strip-components 1 -C ${MANAGERS_DIRECTORY}

# Remove the tarball
rm -rf ${DOWNLOADS}/managers.tar.gz

# Then, ask before continue...
printf "\n"
printf "Please, select an option: \n"
printf "${STYLE} 1 - Bower \n"
printf "${STYLE} 2 - Grunt \n"
printf "${STYLE} 3 - Compass \n"
printf "${STYLE} 4 - Composer \n"
printf "${STYLE} 5 - NPM \n"
printf "${STYLE} 6 - Rake \n"
printf "${STYLE} 7 - Make \n"
printf "${STYLE} 0  - Quit \n"
printf "\n"
read -p "Enter your choice: " input

if [ $input = "1" ]; then

    # copy files to ./src folder
    e_header "Copying files..."
    mv ${MANAGERS_DIRECTORY}/${BOWER}/* ${MANAGERS_DIRECTORY}

    # remove unecessary folders
    e_header "Removing stuff you don't want..."
    cd ${MANAGERS_DIRECTORY}
    rm -rf README.md init.sh ${BOWER} ${GRUNT} ${COMPASS} ${COMPOSER} ${NPM} ${GEMRAKE} ${MAKEFILE}

    # Everything is ok!
    e_success "Ready to rock with Bower!"

fi

if [ $input = "2" ]; then

    # copy files to ./src folder
    e_header "Copying files..."
    mv ${MANAGERS_DIRECTORY}/${GRUNT}/* ${MANAGERS_DIRECTORY}

    # remove unecessary folders
    e_header "Removing stuff you don't want..."
    cd ${MANAGERS_DIRECTORY}
    rm -rf README.md init.sh ${BOWER} ${GRUNT} ${COMPASS} ${COMPOSER} ${NPM} ${GEMRAKE} ${MAKEFILE}

    # Everything is ok!
    e_success "Ready to rock with Grunt!"

fi

if [ $input = "3" ]; then

    # copy files to ./src folder
    e_header "Copying files..."
    mv ${MANAGERS_DIRECTORY}/${COMPASS}/* ${MANAGERS_DIRECTORY}

    # remove unecessary folders
    e_header "Removing stuff you don't want..."
    cd ${MANAGERS_DIRECTORY}
    rm -rf README.md init.sh ${BOWER} ${GRUNT} ${COMPASS} ${COMPOSER} ${NPM} ${GEMRAKE} ${MAKEFILE}

    # Everything is ok!
    e_success "Ready to rock with Compass!"

fi

if [ $input = "4" ]; then

    # copy files to ./src folder
    e_header "Copying files..."
    mv ${MANAGERS_DIRECTORY}/${COMPOSER}/* ${MANAGERS_DIRECTORY}

    # remove unecessary folders
    e_header "Removing stuff you don't want..."
    cd ${MANAGERS_DIRECTORY}
    rm -rf README.md init.sh ${BOWER} ${GRUNT} ${COMPASS} ${COMPOSER} ${NPM} ${GEMRAKE} ${MAKEFILE}

    # Everything is ok!
    e_success "Ready to rock with Composer!"

fi

if [ $input = "5" ]; then

    # copy files to ./src folder
    e_header "Copying files..."
    mv ${MANAGERS_DIRECTORY}/${NPM}/* ${MANAGERS_DIRECTORY}

    # remove unecessary folders
    e_header "Removing stuff you don't want..."
    cd ${MANAGERS_DIRECTORY}
    rm -rf README.md init.sh ${BOWER} ${GRUNT} ${COMPASS} ${COMPOSER} ${NPM} ${GEMRAKE} ${MAKEFILE}

    # Everything is ok!
    e_success "Ready to rock with NPM!"

fi

if [ $input = "6" ]; then

    # copy files to ./src folder
    e_header "Copying files..."
    mv ${MANAGERS_DIRECTORY}/${GEMRAKE}/* ${MANAGERS_DIRECTORY}

    # remove unecessary folders
    e_header "Removing stuff you don't want..."
    cd ${MANAGERS_DIRECTORY}
    rm -rf README.md init.sh ${BOWER} ${GRUNT} ${COMPASS} ${COMPOSER} ${NPM} ${GEMRAKE} ${MAKEFILE}

    # Everything is ok!
    e_success "Ready to rock with Rake!"

fi

if [ $input = "7" ]; then

    # copy files to ./src folder
    e_header "Copying files..."
    mv ${MANAGERS_DIRECTORY}/${MAKEFILE}/* ${MANAGERS_DIRECTORY}

    # remove unecessary folders
    e_header "Removing stuff you don't want..."
    cd ${MANAGERS_DIRECTORY}
    rm -rf README.md init.sh ${BOWER} ${GRUNT} ${COMPASS} ${COMPOSER} ${NPM} ${GEMRAKE} ${MAKEFILE}

    # Everything is ok!
    e_success "Ready to rock with Make!"

fi

if [ $input = "0" ]; then
    e_success "Bye bye!"
    exit
fi
