#!/bin/bash

# up to you (me) if you want to run this as a file or copy paste at your leisure

# Shell Script for Initialize a new project (based on my needs)
# run with alias "newproject"

# Ask for the administrator password upfront
sudo -v

# Let's start with some settings
BOILERPLATES_DIRECTORY="${HOME}/.forcefiles/init/boilerplates"
STYLE="$(tput setaf 37)$(tput bold)[ ? ]$(tput sgr0)"

# Let me introduce myself
clear
figlet -f smslant a new project will be born

# Then, ask before continue...
printf "\n"
printf "You're about to start a new project. Please, select an option to getting started (0-9). \n"
printf "\n"
printf "${STYLE} 0 - General \n"
printf "${STYLE} 1 - WordPress \n"
printf "${STYLE} 2 - Mobile \n"
printf "${STYLE} 3 - Node \n"
printf "${STYLE} 4 - Ghost \n"
printf "${STYLE} 5 - Jekyll \n"
printf "${STYLE} 6 - DocPad \n"
printf "${STYLE} 7 - Assemble \n"
printf "${STYLE} 8 - Rails \n"
printf "\n"
printf "${STYLE} q  - Quit \n"
printf "\n"
read -p "Enter your choice: " input

case "$input" in

    0) bash ${BOILERPLATES_DIRECTORY}/general exit 0 ;;
    1) bash ${BOILERPLATES_DIRECTORY}/wordpress exit 0 ;;
    2) bash ${BOILERPLATES_DIRECTORY}/mobile exit 0 ;;
    3) bash ${BOILERPLATES_DIRECTORY}/node exit 0 ;;
    4) bash ${BOILERPLATES_DIRECTORY}/ghost exit 0 ;;
    5) bash ${BOILERPLATES_DIRECTORY}/jekyll exit 0 ;;
    6) bash ${BOILERPLATES_DIRECTORY}/docpad exit 0 ;;
    7) bash ${BOILERPLATES_DIRECTORY}/assemble exit 0 ;;
    8) bash ${BOILERPLATES_DIRECTORY}/rails exit 0 ;;
    q | quit) printf "Bye bye!" exit 0 ;;
    *) printf "Invalid option! Try again" exit 0 ;;

esac

# ====================================================
#  TODO - TEST PROJECTS
# ====================================================

# General ✔
# WordPress
# Mobile
# Node
# Ghost
# Jekyll
# DocPad
# Assemble
# Rails
