#!/bin/sh

# up to you (me) if you want to run this as a file or copy paste at your leisure

# Shell Script for Initialize a new project (based on my needs)
# run with alias "newproject"

# Ask for the administrator password upfront
sudo -v

# Let's start with some settings
BOILERPLATES_DIRECTORY="${HOME}/.forcefiles/init/boilerplates"

# Let me introduce myself
clear
figlet A New project will born...

# Then, ask before continue...
printf "\n"
printf "You're about to start a new project. Please, select an option to getting started. \n"
printf "\n"
printf "[ 1 ] - General \n"
printf "[ 2 ] - WordPress \n"
printf "[ 3 ] - Rails \n"
printf "[ 4 ] - Node \n"
printf "[ 5 ] - Ghost \n"
printf "[ 6 ] - Jekyll \n"
printf "[ 7 ] - DocPad \n"
printf "\n"
printf "[ 0 ] - Exit \n"
printf "\n"
read -p "Enter your choice: " input

if [ $input = "1" ]; then
    bash ${BOILERPLATES_DIRECTORY}/general
fi

if [ $input = "2" ]; then
    bash ${BOILERPLATES_DIRECTORY}/wordpress
fi

if [ $input = "3" ]; then
    bash ${BOILERPLATES_DIRECTORY}/rails
fi

if [ $input = "4" ]; then
    bash ${BOILERPLATES_DIRECTORY}/node
fi

if [ $input = "5" ]; then
    bash ${BOILERPLATES_DIRECTORY}/ghost
fi

if [ $input = "6" ]; then
    bash ${BOILERPLATES_DIRECTORY}/jekyll
fi

if [ $input = "7" ]; then
    bash ${BOILERPLATES_DIRECTORY}/docpad
fi

if [ $input = "0" ]; then
    printf "Bye bye!"
    exit
fi


# ====================================================
#  TODO - TEST PROJECTS
# ====================================================

# General ✔
# WordPress
# Rails
# Node
# Ghost
# Jekyll
# DocPad
