#!/bin/bash

# ------------------------------------------------------------------------------
# | Install applications                                                       |
# ------------------------------------------------------------------------------

run_apps() {

    # Install apps
    e_header "Installing Applications"

    brew cask install apache-couchdb firefox psequel spotify xamarin-studio appcleaner fluid imageoptim sequel-pro thunderbird google-adwords-editor ionic-lab sketch tomighty google-chrome macvim sketch-toolbox slack visual-studio-code dropbox google-drive messenger skype wercker filezilla google-hangouts mysqlworkbench sourcetree xamarin-android-player virtualbox vagrant robomongo teamviewer coconutbattery docker fontprep glueprint numi shuttle spectacle

    e_success "Apps successfully installed!"

    e_info "--------------------------------------------------------------------------"
    e_info "Remember to install:"
    e_info "Wunderlist, MeisterTask, Adobe Family, Postman and Slack outo of this box!"
    e_info "--------------------------------------------------------------------------"

}