#!/bin/bash

# ------------------------------------------------------------------------------
# | Install applications                                                       |
# ------------------------------------------------------------------------------

run_apps() {

    # Install apps
    brew tap phinze/homebrew-cask
    brew install brew-cask

    local -a list_apps=(
        "appcleaner"
        "firefox"
        "sublime-text"
        "filezilla"
        "imageoptim"
        "dropbox"
        "mou"
        "sparrow"
        "skype"
        "feeds"
        "screenflow"
        "sourcetree"
        "limechat"
        "google-drive"
    )

    brew cask install $list_apps
    [[ $? ]] && e_success "All apps installed successfully!"

}
