#!/bin/bash

# ------------------------------------------------------------------------------
# | Install applications                                                       |
# ------------------------------------------------------------------------------

run_apps() {

    # Install apps
    e_header "Installing Applications"

    brew cask install apache-couchdb psequel spotify appcleaner imageoptim google-adwords-editor sketch google-chrome sketch-toolbox slack visual-studio-code dropbox google-drive messenger skype wercker filezilla google-hangouts sourcetree virtualbox docker shuttle genymotion postmam

    e_success "Apps successfully installed!"

    e_info "--------------------------------------------------------------------------"
    e_info "Remember to install:"
    e_info "Wunderlist, MeisterTask, Adobe Family and Postman out of this box!"
    e_info "--------------------------------------------------------------------------"

}
