#!/bin/bash

# ------------------------------------------------------------------------------
# | Homebrew Settings                                                          |
# ------------------------------------------------------------------------------

run_brew() {

    # Check for Homebrew
    if type_exists "brew"; then

        # Use the latest version of Homebrew
        e_header "Updating Homebrew"
        brew update
        e_success "Done!"

        # Upgrade any already-installed formulae
        e_header "Updating any existing Homebrew formulae"
        brew upgrade
        e_success "Done"

        # Install formulaes
        e_header "Installing Homebrew formulae"

        # Languages - Erlang is a dependency of Couch DB.
        brew install erlang 

        # Languages Utilities
        brew install nvm

        # Dependencies
        brew install coreutils findutils freetype isl011 gettext pcre pkg-config unixodbc gmp4 readline mpfr2 wxmac autoconf automake openssl icu4c figlet bash bash-completion tree jpeg lzlib discount ctags gdb wget ack optipng imagemagick gifsicle ffmpeg watchman potrace

        # Tools
        brew install git-flow-avh htop-osx tmux macvim terminal-notifier # Install Git if is not running @ OS.
        brew install vim --with-override-system-vi
        brew install homebrew/versions/gcc46
        brew install homebrew/dupes/rsync

        # Services
        brew tap gapple/services
        brew tap homebrew/dupes
        brew tap homebrew/versions
        brew tap homebrew/php
        brew tap homebrew/apache
        
        # Link Apps
        brew linkapps python terminal-notifier macvim

        e_success "Homebrew formulaes successfully installed!"

    else

        printf "\n"
        e_error "Error: Homebrew not found."
        printf "Aborting...\n"
        exit

    fi

}
