#!/bin/bash

# ------------------------------------------------------------------------------
# | Homebrew Settings                                                          |
# ------------------------------------------------------------------------------

run_brew() {

    # Check for Homebrew
    if type_exists "brew"; then

        # Use the latest version of Homebrew
        e_header "Updating Homebrew..."
        brew update
        e_success "Done"

        # Upgrade any already-installed formulae
        e_header "Updating any existing Homebrew formulae..."
        brew upgrade
        e_success "Done"

        # Install formulaes
        e_header "Installing Homebrew formulae..."
        local -a list_formulaes=(
            "autoconf"
            "automake"
            "libtool"
            "libyaml"
            "libxslt"
            "libksba"
            "openssl"
            "coreutils"
            "findutils"
            "figlet"
            "bash"
            "bash-completion"
            "wget"
            "ack"
            "tree"
            "gcc46"
            "apple-gcc42"
            "git"
            "jpeg"
            "optipng"
            "imagemagick"
            "node"
            "phantomjs"
            "mongodb"
            "erlang"
            "elixir"
            "macvim"
            "discount"
            "ctags"
            "https://raw.github.com/Homebrew/homebrew-dupes/master/rsync.rb"
        )

        brew install $list_formulaes
        brew install vim --override-system-vi
        e_success "Formulaes installed successfully!"

        # Remove outdated versions from the Cellar
        brew cleanup

    else

        printf "\n"
        e_error "Error: Homebrew not found."
        printf "Aborting...\n"
        exit

    fi

}
