#!/bin/bash

# ------------------------------------------------------------------------------
# | My Text Editor Settings                                                    |
# ------------------------------------------------------------------------------

run_editors() {

    # Sublime Text Settings
    cd ~/Library/Application\ Support/Sublime\ Text\ 2/Packages/
    rm -r User
    ln -s ~/Dropbox/Github/setup-subl/User

    # VIM Settings
    cd ~ && bash -c "$(curl -fsSL raw.github.com/vitorbritto/setup-vim/master/init.sh)"

    # Atom Settings
    cd ~ && bash -c "$(curl -fsSL raw.github.com/vitorbritto/setup-atom/master/init.sh)"

}
