#!/bin/bash

# ------------------------------------------------------------------------------
# | Install gems                                                               |
# ------------------------------------------------------------------------------

run_gems() {

    # Check for Homebrew
    if type_exists "gem"; then

        # Use the latest version of gem
        e_header "Updating gem..."
        gem update --system
        e_success "Done"

        # Upgrade any already-installed gem
        e_header "Updating any installed gem..."
        gem update
        e_success "Done"

        local -a list_gems=(
            "sass"
            "compass"
            "haml"
            "jekyll"
            "showterm"
            "bundler"
            "capistrano"
            "sinatra"
            "rails"
        )

        # Install gems
        e_header "Installing missing gems..."
        gem install sass -v 3.2.19 # Install previous version of Sass for secutiry
        gem install $list_gems     # Install listed gems
        gem install compass --pre  # Install pre-release of compass to work with Sass v3.3.x
        e_success "Gems successfully installed!"

    else

        printf "\n"
        e_error "Error: gem not found."
        printf "Aborting...\n"
        exit

    fi

}
