#!/bin/bash

# ------------------------------------------------------------------------------
# | Install gems                                                               |
# ------------------------------------------------------------------------------

run_gems() {

    # Check for Homebrew
    if type_exists "gem"; then

        # Use the latest version of gem
        e_header "Updating gem..."
        gem update --system
        [[ $? ]] && e_success "Done"

        # Upgrade any already-installed gem
        e_header "Updating any installed gem..."
        gem update
        [[ $? ]] && e_success "Done"

        local -a list_gems=(
            "rails"
            "sass"
            "compass"
            "haml"
            "jekyll"
            "showterm"
            "bundler"
            "capistrano"
            "sinatra"
        )

        # Install gems
        e_header "Installing missing gems..."
        sudo gem install $list_gems
        gem install sass -v 3.2.19

        [[ $? ]] && e_success "Gems installed successfully!"

    else

        printf "\n"
        e_error "Error: gem not found."
        printf "Aborting...\n"
        exit

    fi

}
