#!/bin/bash

# ------------------------------------------------------------------------------
# | Everybody need some help                                                   |
# ------------------------------------------------------------------------------

run_help() {

cat <<EOT

------------------------------------------------------------------------------
OS X dotfiles - Vitor Britto - http://www.vitorbritto.com.br
------------------------------------------------------------------------------

Usage: $(basename "$0") [options]

Options:
    -h, --help      Print this help text
    -l, --list      Print a list of additional software to install
    --no-packages   Suppress package updates
    --no-sync       Suppress pulling from the remote repository

Documentation can be found at https://github.com/vitorbritto/forcefiles/

Copyright (c) Vitor Britto
Licensed under the MIT license.

------------------------------------------------------------------------------

EOT

}
