#!/bin/bash

# ------------------------------------------------------------------------------
# | List what it'll be installed                                               |
# ------------------------------------------------------------------------------

run_list() {

cat <<EOT

------------------------------------------------------------------------------
OS X dotfiles - Vitor Britto - http://www.vitorbritto.com
------------------------------------------------------------------------------

This will install/update the following stuff to improve my workflow.


Packages
------------

Brew:
    git
    ack
    bash-completion
    jpeg
    node
    git-ftp
    optipng
    phantomjs
    mongodb
    tree
    imagemagick
    wget

NPM:
    yo
    grunt-cli
    bower
    grunt-init
    generator-generator
    nave
    ungit
    docpad
    imageoptim-cli
    jade
    stylus
    jshint
    karma
    express@3.4.3
    mongoose
    mongodb
    browserify

Dependencies:
    Z
    Pygments

Rvm:
    Ruby - 1.9.3
    Ruby - 2.0.0

Gems:
    Rails
    Sass
    Compass
    Jekyll

PHP:
    Update PHP version from 5.3 to 5.4
    MySQL and phpMyAdmin


Applications
------------

Browsers:
    Firefox Aurora
    Google Chrome
    Google Chrome Canary
    Opera Next

Development:

    Sublime Text 3
    SourceTree
    FileZilla
    VirtualBox (w/ Vagrant)
    Image Optim

Others:
    Mou
    Alfred
    Dropbox
    Skype
    Transmission
    VLC

Sublime:
    Sync data to config my ST3

------------------------------------------------------------------------------

EOT

}
