#!/bin/bash

# ------------------------------------------------------------------------------
# | Mobile Settings                                                            |
# ------------------------------------------------------------------------------

run_mobile() {

    e_header "Setting up your Mobile Environment"

    e_warning "IMPORTANT: You need to accept the XCode License to procced..."
    xcodebuild -license

    e_header "Installing Gems"
    sudo gem install xcodeproj cocoapods

    e_header "Setting up CocoaPods Master Repository"
    mkdir -p ~/.cocoapods/repos && cd ~/.cocoapods/repos && git clone https://github.com/CocoaPods/Specs.git master

    e_header "Installing Formulaes"
    brew install xcproj android-sdk ideviceinstaller ios-webkit-debug-proxy

    e_info "Remember to get Genymotion (https://www.genymotion.com/)"

    e_success "All done!"

}
