#!/bin/bash

# ------------------------------------------------------------------------------
# | NGINX Settings                                                             |
# ------------------------------------------------------------------------------

run_nginx() {

    e_header "Installing NGINX"

    brew install -v nginx

    e_header "Setting up NGINX"

    sudo cp -v /usr/local/opt/nginx/*.plist /Library/LaunchDaemons/
    sudo chown root:wheel /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
    sudo launchctl unload /Library/LaunchDaemons/homebrew.mxcl.nginx.plist

}