#!/bin/bash

# ------------------------------------------------------------------------------
# | NPM Settings                                                               |
# ------------------------------------------------------------------------------

run_npm() {

    # Check for npm
    if type_exists "npm"; then
        e_header "Installing NPM modules..."

        # List of npm packages
        local packages="grunt-cli gulp bower express imageoptim-cli docpad nave browserify beefy shelljs uglify-js jshint csslint csscomb stylus coffee-script browser-sync karma markdown pageres jade harp jasmine-node mocha coveralls nightwatch"

        # Install packages globally and quietly
        npm install $packages -g

        [[ $? ]] && e_success "Done"
    else
        printf "\n"
        e_error "Error: npm not found."
        printf "Aborting...\n"
        exit
    fi

}
