#!/bin/bash

# ------------------------------------------------------------------------------
# | NPM Settings                                                               |
# ------------------------------------------------------------------------------

run_npm() {

    # Check for npm
    if type_exists "npm"; then
        e_header "Installing NPM modules..."

        # List of npm packages
        local packages="
        yo
        grunt-cli
        bower
        grunt-init
        generator-generator
        ungit
        nave
        browserify
        docpad
        imageoptim-cli
        dalek-cli
        sails
        express@3.3.4"

        # Install packages globally and quietly
        npm install $packages -g

        [[ $? ]] && e_success "Done"
    else
        printf "\n"
        e_error "Error: npm not found."
        printf "Aborting...\n"
        exit
    fi

}
