#!/bin/bash

# ------------------------------------------------------------------------------
# | NPM Settings                                                               |
# ------------------------------------------------------------------------------

run_npm() {

    # Check for npm
    if type_exists "npm"; then

        # Install packages globally and quietly
        e_header "Installing Node packages"

        npm install -g grunt-cli gulp bower imageoptim-cli nave browserify shelljs uglifyjs jshint eslint stylus browser-sync markdown jade harp mocha coveralls istanbul yslow tictac phantomas psi webpagetest babel react-tools webpack obfuscator clean-css node-sass express karma pm2 beefy yo hoodie-cli plato ionic cordova electron-prebuilt typescript

        e_success "Node packages successfully installed!"

    else

        printf "\n"
        e_error "Error: npm not found."
        printf "Aborting...\n"
        exit

    fi

}
