#!/bin/bash

# ------------------------------------------------------------------------------
# | NVM Settings                                                               |
# ------------------------------------------------------------------------------

run_nvm() {

    if type_exists "nvm"; then
        e_header "Installing nvm dependencies"
        nvm install v8.9.4
        nvm install v9.4.0
        ln -s $(brew --prefix nvm)/nvm.sh ~/.nvm/nvm.sh     # Symlink (optional)
        nvm alias default 8.9.4
        brew update
        brew upgrade nvm
    else
        printf "\n"
        e_error "Error: nvm not found."
        printf "Aborting...\n"
        exit
    fi

}
