#!/bin/bash

# ------------------------------------------------------------------------------
# | Update PHP environment                                                     |
# ------------------------------------------------------------------------------

run_php() {

    # Upgrade PHP version (from 5.3 to 5.4)
    brew tap homebrew/dupes
    brew tap josegonzalez/homebrew-php
    brew install php54 --with-mysql --wihout-apache
    brew install php54-memcached php54-apc php54-xdebug

    printf "Done!"
    printf "\n"
    printf "-------------------------------------------------------------------------"
    printf "SETUP APACHE\n"
    printf "Remember to uncomment the following lines in your httpd.conf\n"
    printf "1. Execute: sudo nano -w /etc/apache2/httpd.conf\n"
    printf "2. Active PHP: LoadModule php5_module libexec/apache2/libphp5.so\n"
    printf "3. Active Virtual Host: Include /private/etc/apache2/extra/httpd-vhosts.conf\n"
    printf "-------------------------------------------------------------------------"
    printf "\n"


    # Install MySQL and phpmyadmin
    # -------------------------------------
    # http://coolestguyplanettech.com/downtown/install-and-configure-apache-mysql-php-and-phpmyadmin-osx-108-mountain-lion

}
