#!/bin/bash

# ------------------------------------------------------------------------------
# | phpmyadmin Settings                                                        |
# ------------------------------------------------------------------------------

run_pma() {

    e_header "Installing phpmyadmin"

    brew install -v phpmyadmin

    e_header "Setting up MySQL"

    cat >> $(brew --prefix)/etc/apache2/2.2/httpd.conf <<'EOF'

# Webserver configuration
Alias /phpmyadmin /usr/local/share/phpmyadmin
<Directory /usr/local/share/phpmyadmin/>
Options Indexes FollowSymLinks MultiViews
AllowOverride All
<IfModule mod_authz_core.c>
  Require all granted
</IfModule>
<IfModule !mod_authz_core.c>
  Order allow,deny
  Allow from all
</IfModule>
</Directory>
EOF

    e_success "phpmyadmin successfully installed!"

}


