#!/bin/bash

# ------------------------------------------------------------------------------
# | Installing my Rubies                                                       |
# ------------------------------------------------------------------------------

run_rubies() {

    # Check for rvm
    if type_exists "rvm"; then
        e_header "Installing Ruby..."

        # Instal versions 1.9.3 and 2.0.0
        rvm install 1.9.3
        rvm install 2.0.0

        # Use by default version 2.0.0
        rvm use 2.0.0 --default
        e_success "Done"

        echo "-------------------------------------------------------------------------------------------------"
        echo "IMPORTANT NOTE"
        echo "Check if Ruby version is 2.0.0. If not, Rails will not be installed."
        echo "Run: 'rvm use 2.0.0 --default' and then install Rails gem."
        echo "-------------------------------------------------------------------------------------------------"

    else
        printf "\n"
        e_error "Error: rvm not found."
        printf "Aborting...\n"
        exit
    fi

}
