#!/bin/bash

# ------------------------------------------------------------------------------
# | Log Messages                                                               |
# ------------------------------------------------------------------------------

# Header logging
e_header() {
    printf "$(tput setaf 38)→ %s$(tput sgr0)\n" "$@"
}

# Success logging
e_success() {
    printf "$(tput setaf 76)✔ %s$(tput sgr0)\n" "$@"
}

# Error logging
e_error() {
    printf "$(tput setaf 1)✖ %s$(tput sgr0)\n" "$@"
}

# Warning logging
e_warning() {
    printf "$(tput setaf 3)! %s$(tput sgr0)\n" "$@"
}

# Ask for confirmation before proceeding
seek_confirmation() {
    printf "\n"
    e_warning "$@"
    read -p "Continue? (y/n) " -n 1
    printf "\n"
}

# Test whether the result of an 'ask' is a confirmation
is_confirmed() {
    if [[ "$REPLY" =~ ^[Yy]$ ]]; then
      return 0
    fi
    return 1
}

# Test whether we're in a git repo
is_git_repo() {
    $(git rev-parse --is-inside-work-tree &> /dev/null)
}

# Test whether a command exists
# $1 - cmd to test
type_exists() {
    if [ $(type -P $1) ]; then
      return 0
    fi
    return 1
}

# Test whether a directory exists
# $1 - cmd to test
dir_exists() {
    if [ $(-d $1) ]; then
      return 0
    fi
    return 1
}

# Test whether a Homebrew formula is already installed
# $1 - formula name (may include options)
formula_exists() {
    if $(brew list $1 > /dev/null); then
        printf "%s already installed.\n" "$1"
        return 0
    fi

    e_warning "Missing formula: $1"
    return 1
}


# ------------------------------------------------------------------------------
# | List what it'll be installed                                               |
# ------------------------------------------------------------------------------

run_list() {

cat <<EOT

------------------------------------------------------------------------------
OS X dotfiles - Vitor Britto - http://www.vitorbritto.com.br
------------------------------------------------------------------------------

This will install/update the following stuff to improve my workflow.


Packages
------------

Brew:
    - scala
    - ocaml
    - erlang
    - elixir
    - clojure14
    - opam
    - nvm
    - nodejs
    - iojs
    - leiningen
    - mongodb
    - postgresql
    - sqlite
    - coreutils
    - findutils
    - libksba
    - libtool
    - libyaml
    - libxslt
    - libmemcached
    - libmpc08
    - libpng
    - libevent
    - libgpg-error
    - libtiff
    - freetype
    - isl011
    - gettext
    - memcached
    - pcre
    - pkg-config
    - unixodbc
    - cloog018
    - gmp4
    - readline
    - mpfr2
    - wxmac
    - autoconf
    - automake
    - openssl
    - icu4c
    - figlet
    - bash
    - bash-completion
    - tree
    - gcc46
    - apple-gcc42
    - jpeg
    - zlib
    - discount
    - ctags
    - gdb
    - wget
    - ack
    - optipng
    - imagemagick
    - git
    - htop-osx
    - tmux
    - macvim
    - rsync
    - terminal-notifier
    - nginx
    - httpd22
    - phpmyadmin
    - php56
    - php56-opcache
    - php-cs-fixer

NPM:
    - grunt-cli
    - gulp
    - jshint
    - jscs
    - clean-css
    - eslint
    - babel-eslint
    - babel
    - pm2
    - browser-sync
    - jspm
    - phantomjs-prebuilt
    - casperjs@1.1.0-beta4
    - slimerjs
    - dalek-cli
    - cucumber
    - pioneer
    - mocha
    - coveralls
    - istanbul
    - karma
    - protractor
    - typescript
    - stylus
    - pug
    - node-sass
    - lodash
    - uglifyjs
    - express
    - shelljs
    - npm-check
    - cbt_tunnels
    - aglio
    - surge
    - phantomas
    - psi
    - webpagetest
    - plato
    - yslow
    - ionic
    - cordova
    - ios-sim
    - ios-deploy
    - electron-prebuilt
    - add-cors-to-couchdb
    - nodal
    - firebase-tools
    - firebase-bolt
    - esdoc
    - sassdoc


Dependencies:
    - Pygments

Rubies (only for OSX Lion):
    - Ruby - 1.9.3
    - Ruby - 2.0.0

Gems:
    - sass
    - compass
    - haml
    - slim
    - jekyll
    - bundler
    - capistrano
    - sinatra
    - rack
    - puma
    - homesick
    - capybara
    - rspec
    - rails
    - showterm

PHP:
    - composer
    - wp-cli


Applications
------------

    - appcleaner
    - firefox
    - sublime-text
    - macvim
    - filezilla
    - imageoptim
    - dropbox
    - mou
    - skype
    - feeds
    - sourcetree
    - google-drive
    - google-chrome
    - evernote
    - komanda
    - axure-rp-pro
    - sequel-pro
    - transmission
    - spotify
    - virtualbox
    - vagrant
    - sketch
    - hipchat
    - slack
    - robomongo
    - thunderbird
    - unrarx
    - psequel
    - apache-couchdb
    - gitter
    - fluid
    - trello-x
    - wercker
    - atom
    - haskell-platform

------------------------------------------------------------------------------

EOT

}


# ------------------------------------------------------------------------------
# | Everybody need some help                                                   |
# ------------------------------------------------------------------------------

run_help() {

cat <<EOT

------------------------------------------------------------------------------
OS X dotfiles - Vitor Britto - http://www.vitorbritto.com.br
------------------------------------------------------------------------------

Usage: $(basename "$0") [options]

Options:
    -h, --help      output help
    -l, --list      output list of dependencies and applications
    --no-packages   suppress package updates
    --no-sync       suppress pulling from the remote repository

Documentation can be found at https://github.com/vitorbritto/forcefiles/

Copyright (c) Vitor Britto
Licensed under the MIT license.

------------------------------------------------------------------------------

EOT

}
