#!/bin/bash

# ------------------------------------------------------------------------------
# | WordPress Settings                                                         |
# ------------------------------------------------------------------------------

run_wordpress() {

    # Install CLI
    e_header "Installing WordPress CLI"

    curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    php wp-cli.phar --info
    chmod +x wp-cli.phar
    mv wp-cli.phar /usr/local/bin/wp

    e_success "WordPress CLI successfully installed!"

    # Install Completions
    e_header "Installing WordPress Bash Completions"

    curl -O https://raw.githubusercontent.com/wp-cli/wp-cli/master/utils/wp-completion.bash
    chmod +x wp-completion.bash
    mv wp-completion.bash /usr/local/etc/bash_completion.d

    e_success "WordPress Bash Completions successfully installed!"

}
