#!/bin/bash

#
# Paths
# ---------------------------------------------------

# Directories to be prepended to PATH
declare -a dirs_to_prepend=(
    "$(brew --prefix)/bin"
    "/usr/local/sbin"
    "$(brew --prefix)/mysql/bin"
    "/Library/Frameworks/Python.framework/Versions/3.7/bin"
    "$HOME/.yarn/bin"
)

# Directories to be appended to PATH
declare -a dirs_to_append=(
    "/usr/local/bin"
    "$HOME/.forcefiles/bin"
    "$HOME/.composer/vendor/bin"
    "$(brew --prefix coreutils)/libexec/gnubin"
    "$ANDROID_HOME/tools"
    "$ANDROID_HOME/tools/bin"
    "$ANDROID_HOME/platform-tools"
    "$JAVA_HOME/bin"
    "$HOME/.config/yarn/global/node_modules/.bin"
)

# Prepend directories to PATH
for index in ${!dirs_to_prepend[*]}
do
    if [ -d ${dirs_to_prepend[$index]} ]; then
        # If these directories exist, then prepend them to existing PATH
        PATH="${dirs_to_prepend[$index]}:$PATH"
    fi
done

# Append directories to PATH
for index in ${!dirs_to_append[*]}
do
    if [ -d ${dirs_to_append[$index]} ]; then
        # If these bins exist, then append them to existing PATH
        PATH="$PATH:${dirs_to_append[$index]}"
    fi
done

unset dirs_to_prepend dirs_to_append

export PATH
