#!/bin/bash

#
# Profile
# ---------------------------------------------------


declare -a files=(
    $HOME/.forcefiles/bash/bash_options   # Options
    $HOME/.forcefiles/bash/bash_exports   # Exports
    $HOME/.forcefiles/bash/bash_aliases   # Aliases
    $HOME/.forcefiles/bash/bash_functions # Functions
    $HOME/.forcefiles/bash/bash_prompt    # Custom bash prompt
    $HOME/.bash_profile.local             # Local and private settings
    $HOME/.forcefiles/bash/bash_paths     # Path modifications
)

# If these files are readable, source them
for index in ${!files[*]}
do
    if [[ -r ${files[$index]} ]]; then
        source ${files[$index]}
    fi
done

unset files

# Source nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
# export ANDROID_HOME=/usr/local/share/android-sdk