#!/bin/bash

#
# Profile
# ---------------------------------------------------


declare -a files=(
    $HOME/.forcefiles/bash/bash_options   # Options
    $HOME/.forcefiles/bash/bash_exports   # Exports
    $HOME/.forcefiles/bash/bash_aliases   # Aliases
    $HOME/.forcefiles/bash/bash_functions # Functions
    $HOME/.forcefiles/bash/bash_prompt    # Custom bash prompt
    $HOME/.bash_profile.local             # Local and private settings
    $HOME/.forcefiles/bash/bash_paths     # Path modifications
)

# If these files are readable, source them
for index in ${!files[*]}
do
    if [[ -r ${files[$index]} ]]; then
        source ${files[$index]}
    fi
done

unset files

# bash_completion_path="$(brew --prefix)/etc/bash_completion"
bash_completion_path="$NVM_DIR/bash_completion"
nvm_path="$NVM_DIR/nvm.sh"

# Source Bash completion
if [[ -r $bash_completion_path ]]; then
    source $bash_completion_path
fi

# Source nvm
[[ -s $nvm_path ]] && source $nvm_path 

# export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
# export ANDROID_HOME=/usr/local/share/android-sdk