#!/bin/bash

#
# Paths
# ---------------------------------------------------

# Directories to be prepended to PATH
declare -a dirs_to_prepend=(
    "$(brew --prefix)/bin"                      # Ensure that this bin always takes precedence over
    "/usr/local/sbin"
    "$(brew --prefix)/mysql/bin"                # Add MySQL to PATH
    "$(brew --prefix)/mongodb/bin"              # Add MongoDB to PATH
    "$HOME/Library/Haskell/bin"                 # Add GHC-platform/Haskell to PATH
)

# Directories to be appended to PATH
declare -a dirs_to_append=(
    "/usr/bin"                                  # Add user directory to PATH
    "$HOME/bin"                                 # Add home directory to PATH
    "$HOME/.forcefiles/bin"                     # Add .forcefiles directory to PATH
    "$HOME/.rvm/bin"                            # Add RVM to PATH for scripting
    "$(brew --prefix coreutils)/libexec/gnubin" # Add brew-installed GNU core utilities bin
    "$(brew --prefix)/share/npm/bin"            # Add npm to PATH
    "$(brew --prefix)/share/scala/bin"          # Add Scala to PATH
)
# Prepend directories to PATH
for index in ${!dirs_to_prepend[*]}
do
    if [ -d ${dirs_to_prepend[$index]} ]; then
        # If these directories exist, then prepend them to existing PATH
        PATH="${dirs_to_prepend[$index]}:$PATH"
    fi
done

# Append directories to PATH
for index in ${!dirs_to_append[*]}
do
    if [ -d ${dirs_to_append[$index]} ]; then
        # If these bins exist, then append them to existing PATH
        PATH="$PATH:${dirs_to_append[$index]}"
    fi
done

unset dirs_to_prepend dirs_to_append

export PATH
