#!/bin/bash

#
# Paths
# ---------------------------------------------------

# Directories to be prepended to PATH
declare -a dirs_to_prepend=(
    "$(brew --prefix)/bin"
    "/usr/local/sbin"
    "$(brew --prefix)/mysql/bin"                            # Add MySQL
    "/Library/Frameworks/Python.framework/Versions/3.7/bin" # Python
    # "$(brew --prefix)/mongodb/bin"                        # Add MongoDB
    # "$(brew --prefix)/psql/bin"                           # Add PostgreSQL
    # "$(brew --prefix)/gettext/bin"                        # Add GetText
)

# Directories to be appended to PATH
declare -a dirs_to_append=(
    "/usr/local/bin"                                      # Add user directory
    "$HOME/.forcefiles/bin"                               # Add .forcefiles directory
    "$HOME/.composer/vendor/bin"                          # Add Composer
    "$(brew --prefix coreutils)/libexec/gnubin"           # Add brew-installed GNU core utilities bin
    "$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools"    # Add Android SDK
    "$JAVA_HOME/bin"                                      # Add Java
)
# Prepend directories to PATH
for index in ${!dirs_to_prepend[*]}
do
    if [ -d ${dirs_to_prepend[$index]} ]; then
        # If these directories exist, then prepend them to existing PATH
        PATH="${dirs_to_prepend[$index]}:$PATH"
    fi
done

# Append directories to PATH
for index in ${!dirs_to_append[*]}
do
    if [ -d ${dirs_to_append[$index]} ]; then
        # If these bins exist, then append them to existing PATH
        PATH="$PATH:${dirs_to_append[$index]}"
    fi
done

unset dirs_to_prepend dirs_to_append

export PATH
