#!/bin/bash

# bash_profile

declare -a files=(
    $HOME/.rvm/scripts/rvm                # Load RVM into a shell session *as a function*
    $HOME/.forcefiles/bash/bash_options   # Options
    $HOME/.forcefiles/bash/bash_exports   # Exports
    $HOME/.forcefiles/bash/bash_aliases   # Aliases
    $HOME/.forcefiles/bash/bash_functions # Functions
    $HOME/.forcefiles/bash/bash_prompt    # Custom bash prompt
    $HOME/.bash_profile.local             # Local and private settings
    $HOME/.forcefiles/bash/bash_paths     # Path modifications
)

# If these files are readable, source them
for index in ${!files[*]}
do
    if [[ -r ${files[$index]} ]]; then
        source ${files[$index]}
    fi
done

unset files

# Only use `brew` after it has been added to the PATH
bash_completion_path="$(brew --prefix)/etc/bash_completion"

# Source Bash completion (installed via Homebrew)
if [[ -r $bash_completion_path ]]; then
    source $bash_completion_path
fi
