#!/bin/bash

#
# Exports
# ---------------------------------------------------

# Make Sublime Text the default editor
export EDITOR="atom -nw"

# Node Version Manager
export NVM_DIR=~/.nvm

# Ignore commands that start with spaces and duplicates
export HISTCONTROL=ignoreboth

# Increase the maximum number of lines contained in the history file
# (default value is 500)
export HISTFILESIZE=5000

# Don't add certain commands to the history file
export HISTIGNORE="&:[bf]g:c:clear:exit:q:ll:ls -l:pwd:* --help"

# Increase the maximum number of commands to remember in the command history
# (default value is 500)
export HISTSIZE=999

# Prefer US English and use UTF-8
export LANG="en_US"
export LC_ALL="en_US.UTF-8"

# Don't clear the screen after quitting a man page
export MANPAGER="less -X"

# Use custom less colors for man pages
# (http://www.gnu.org/software/termutils/manual/termutils-2.0/html_chapter/tput_1.html)
export LESS_TERMCAP_md=$'\E[1;32m'    # begin bold mode
export LESS_TERMCAP_me=$'\E[0m'       # end bold mode

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# Link Homebrew casks in `/Applications` rather than `~/Applications`
export HOMEBREW_CASK_OPTS="--appdir=/Applications --caskroom=/opt/homebrew-cask/Caskroom"

# ARCH FLAGS
export ARCHFLAGS="-arch x86_64"

# JAVA Environment Variable
# export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home"
export JAVA_HOME="/usr/libexec/java_home"

# Android SDK
# export ANDROID_HOME="/usr/local/opt/android-sdk"
export ANDROID_HOME="/usr/local/Cellar/android-sdk/24.3.4"
