#!/bin/bash

#
# bashrc
# ---------------------------------------------------

[ -n "$PS1" ] && source ~/.bash_profile

###-tns-completion-start-###
if [ -f /Users/Colossus/.tnsrc ]; then 
    source /Users/Colossus/.tnsrc 
fi
###-tns-completion-end-###

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
