#!/bin/bash

# Let's start with some settings
ASSEMBLE="assemble"
DOCPAD="docpad"
GENERAL="general"
GHOST="ghost"
JEKYLL="jekyll"
MOBILE="mobile"
NODE="node"
RAILS="rails"
SAILS="sails"
WORDPRESS="wordpress"

DOWNLOADS="${HOME}/Downloads"
BOILERPLATE_DIRECTORY="${HOME}/Sites/projects"
BOILERPLATE_TARBALL_PATH="https://github.com/vitorbritto/boilerplates/tarball/master"
UTILS_DIRECTORY="${HOME}/.forcefiles/lib/utils"

source ${UTILS_DIRECTORY}

# If missing, create directory
if [[ ! -d ${BOILERPLATE_DIRECTORY} ]]; then
    mkdir ${BOILERPLATE_DIRECTORY}
fi

# Get the tarball
e_header "Downloading repository..."
curl -fsSLo ${DOWNLOADS}/boilerplates.tar.gz ${BOILERPLATE_TARBALL_PATH}

# Extract to the boilerplate directory
e_header "Extracting files..."
tar -zxf ${DOWNLOADS}/boilerplates.tar.gz --strip-components 1 -C ${BOILERPLATE_DIRECTORY}

# Remove the tarball
rm -rf ${DOWNLOADS}/boilerplates.tar.gz

# Access main directory
cd ${BOILERPLATE_DIRECTORY}

# Remove unecessary files
e_header "Removing unecessary files..."
rm -rf .gitignore README.md LICENSE
rm -rf ${ASSEMBLE} ${DOCPAD} ${GHOST} ${JEKYLL} ${MOBILE} ${NODE} ${RAILS} ${SAILS} ${WORDPRESS}

# Rename the project
printf "\n"
e_header "Please enter a name for this project (e.g: my-new-project)."
read -p "Project name: " name
mv -f -v general $name && cd $_

# Install Dependencies
seek_confirmation "Would you like to install NPM dependencies?"

if is_confirmed; then
    e_header "Setting up dependencies from NPM..."
    cd src && npm install
fi

# Run Grunt
seek_confirmation "Would you like to run Grunt now?"

if is_confirmed; then
    e_header "Starting Grunt..."
    grunt
fi

# Open Sublime
seek_confirmation "Would you like to open Sublime Text?"

if is_confirmed; then
    e_header "Opening your editor..."
    cd .. && subl .
fi

e_success "All Done!"
