#!/bin/sh

# Let's start with some settings
BOILERPLATE_DIRECTORY="${HOME}/Sites/projects"
BOILERPLATE_TARBALL_PATH="https://github.com/vitorbritto/boilerplates/tarball/master/ghost"
LIBS_DIRECTORY="${HOME}/.forcefiles/lib"
source ${LIBS_DIRECTORY}/utils

# ====================================================
#  WORK IN PROGRESS!!!
# ====================================================
